spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/v1/api/individual-customer/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/v1/api/account/**
        - id: transaction-service
          uri: lb://transaction-service/**
          predicates:
            - Path=/v1/api/transaction
      discovery:
        locator:
          enabled: true
server:
  port: 8889

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: info